### ISSUE TITLE
DataDEX-Change Logo

### ISSUE THREAD

**Issue by Data-DEX** [tomochain/tokens#101]
**Token Address**
https://scan.tomochain.com/address/0x833416c01362659d9f9c2402ad1c110b3a4ed267
**Token Symbol**
DTE
**Token Name**
Data Exchange
**Token Logo**
![256x256](https://user-images.githubusercontent.com/58133604/91003607-fd73d400-e5fb-11ea-8a02-907b213ac7a7.png)

PNG 256px by 256px

**Token Description**
A clear and concise description of the token.
DTE is the official token of DataDEX developed on Tomochain's TRC21 platform.DTE is the payment unit on our ecosystem for all users who want to store assets or buy and sell DTE payments on Our smart contract in early 2021.
**Website**
Link to the website that will use the token.
https://datacoinex.io

**Social links**
e.g Github, telegram, twitter
https://github.com/Data-DEX/tokens

**Comment by khaihkd** [comment]
@Data-DEX pls use correct info (remove sample text)

**Comment by Data-DEX** [comment]
I edited. help me change!

**Comment by WickusCoetzee** [comment]
I changed your logo file (to the pic above) and added it to my pull request.

**Comment by Data-DEX** [comment]
I noticed that our identity logo has not been updated. Please tell me why?https://scan.tomochain.com/tokens/0x833416c01362659d9f9c2402ad1c110b3a4ed267 please check this contract
