### ISSUE TITLE
TAB BANK

### ISSUE THREAD

**Issue by cryptorbank** [tomochain/tokens#110]
**Token Address**
https://scan.tomochain.com/tokens/0x8103bb77ed2035b5da9a3a65d9c313cb6ee41dbd

**Token Symbol**
TAB

**Token Name**
TAB BANK

**Token Logo**
https://drive.google.com/file/d/1pBo8SVvLiH7tOMzg7r8PmXDGsYYbKKh9/view?usp=sharing

**Token Description**
the token using for payment online, and decentralized finance

**Website**
https://tabank.org

**Social links**
https://t.me/joinchat/HOOubhpHap2fyMgs6QiMWw
https://twitter.com/OrgTabank

**Comment by khaihkd** [comment]
done
