### ISSUE TITLE
Halp wanted

### ISSUE THREAD

**Issue by zul15** [tomochain/tokens#113]
**Token Address**
e.g: https://scan.testnet.tomochain.com/address/0x695e4658ab5148be0082534b6fcfd15a6509fe10
**Token Symbol**
e.g: TRD

**Token Name**
e.g: TRON INDO

**Token Logo**
![20200923_201858](https://user-images.githubusercontent.com/52593823/94018860-407fbd80-fddb-11ea-8e42-71246491a8b4.jpg)

**Token Description**
TRON INDO is one of SR of TRON, based on "everyone build,everyone share". TRD will build largest culture zone in TOMO world.

**Website**
http://tronindo.online/

**Social links**
e.g https://t.me/tronindofficial

**Comment by khaihkd** [comment]
wrong contract address
