### ISSUE TITLE
Update token information Love You(LOVE)

### ISSUE THREAD

**Issue by loveyoucoin** [tomochain/tokens#136]
**Token Address**
https://scan.tomochain.com/address/0x22f5db89d9096a677f47ab6a38ff24135de76c77

**Token Symbol**
LOVE

**Token Name**
Love You

**Token Logo**
[0x22f5db89d9096a677f47ab6a38ff24135de76c77 png](https://user-images.githubusercontent.com/76221336/102680718-71f70200-41ed-11eb-916c-1474e4b737c9.png)

**Token Description**
“No matter what, love everyone because everyone is craving love.”

**Website**
https://twitter.com/Love_trc21

**Social links**
https://twitter.com/Love_trc21

**Comment by khaihkd** [comment]
merge
