### ISSUE TITLE
Thay đổi website mới cho token DTE(Data Exchange)

### ISSUE THREAD

**Issue by Data-DEX** [tomochain/tokens#137]
địa chỉ hợp hợp đồng :
0x833416c01362659d9f9c2402ad1c110b3a4ed267

Mã token :
DTE
Tên token :
Data Exchange

**Website cũ https://datacoinex.io Nay chúng tôi chuyển qua website mới là https://datadex.pro giúp chúng tôi cập nhật thông tin mới

**Comment by khaihkd** [comment]
Duplicate #147
