### ISSUE TITLE
Token image update request

### ISSUE THREAD

**Issue by bourbonbreak** [tomochain/tokens#139]
**Token Address**

https://scan.tomochain.com/address/0xb156d1a82fd4aac2f817c0029d7acfdfea031b12

**Token Symbol**
Ttt

**Token Name**
TomoTipToken

**Token Logo** 

![51933282-765A-4F81-A0F8-80B0B118612D](https://user-images.githubusercontent.com/60120529/103369726-e0af4780-4a98-11eb-9a68-ad50903d60de.png)

**Token Description**
A social token used to tip within Tomochain apps.

**Website**
Link to the website that will use the token.

**Social links**
e.g Github, telegram, twitter

**Comment by khaihkd** [comment]
this is not a token address
