### ISSUE TITLE
Add Wrapped UST token info 

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/tokens#145]
**Token Address**
https://scan.tomochain.com/tokens/0xf22a062e59cddc850536b2a538fbbdc4150a783d

**Token Symbol**
UST

**Token Name**
Wrapped UST Token  

**Token Logo**
https://assets.coingecko.com/coins/images/12681/large/UST.png

**Token Description**
The Terra blockchain is secured through distributed consensus over native staked asset Luna, and supports the issuance of price-tracking stablecoins (TerraKRW, TerraUSD, etc.) that are pegged to major world currencies.

**Website**
https://terra.money

**Social links**
Github: https://github.com/terra-project
Twitter: https://twitter.com/terra_money
Discord: https://discord.gg/bYfyhUT
Telegram: https://t.me/TerraLunaChat
Medium: https://medium.com/terra-money
Research forum: https://agora.terra.money/

**Comment by khaihkd** [comment]
@etienne-napoleone can you help me make a pull request
