### ISSUE TITLE
What are the functions of "verifiedlist" and "blacklist" when adding TRC21 token information?

### ISSUE THREAD

**Issue by PomodoroToken** [tomochain/tokens#15]
I have created a token using TomoIssuer and wish to update the token information. What are the purposes of verifiedlist.json and blacklist.json? Do I need to add my token's contract and submit a pull request?

**Comment by drumstoken** [comment]
hey, so. Do you have answer on that question?

**Comment by thanhson1085** [comment]
Team will internally verify the token add to verifiedlist.json
You can report a scam token, but team will ask it to verifiedlist.json
