### ISSUE TITLE
Standardized token symbology for tomo wrapped coins add "tw" or "t" in front

### ISSUE THREAD

**Issue by ttghi** [tomochain/tokens#157]
Hi, would the Tomo team kindly consider a standardized token symbology for Tomo wrapped coins adding "tw" or "t" in front? This would prevent confusion once an erc-20 is wrapped from Ethereum to Tomochain.

As ex. on Ethereum USD Coin would be USDC. While on Tomochain the wrapped version would be twUSDC, or tUSDC.

Kindly provide feedback on the same as I added a dozen tokens to Tomobridge and would kindly request Tomochain feedback before proceeding with any token updates.

thanks,
D

**Comment by thanhson1085** [comment]
Ok, we will consider it.

**Comment by ttghi** [comment]
ty. I edited pull request #149 to not yet include "tw" or "t" pending your feedback. Kindly let me know and If required I can update the token info. tsk, D
