### ISSUE TITLE
Linking TRC21 token from TomoIssuer to github repository

### ISSUE THREAD

**Issue by PomodoroToken** [tomochain/tokens#16]
I have created a TRC21 token on TomoIssuer, and followed the instructions on Github to update token information.

What do I need to do on Github to prove/validate that I am the creator of the TRC21 token on through TomoIssuer? Or is no proof necessary?

**Comment by drumstoken** [comment]
I would like to know it as well.

**Comment by thanhson1085** [comment]
No for now, just create PR or Issue to update the info.
If team need to verify the ownership, we will ask the signing message
