### ISSUE TITLE
GSS 

### ISSUE THREAD

**Issue by Germanstreetstyle** [tomochain/tokens#178]
**Token Address**
e.g: https://scan.tomochain.com/address/0x

**Token Symbol**
e.g: TOMO, KNC

**Token Name**
e.g: TomoChain, Kyber

**Token Logo**
PNG 256px by 256px

**Token Description**
A clear and concise description of the token.

**Website**
Link to the website that will use the token.

**Social links**
e.g Github, telegram, twitter

**Comment by khaihkd** [comment]
no have info
