### ISSUE TITLE
Help Wanted: Update Token Information of EXEES2

### ISSUE THREAD

**Issue by phucdt1713** [tomochain/tokens#182]
**Token Address**
https://scan.tomochain.com/address/0x35c59bf2aa7ecb5a57fb011a4e763da6bae61445

**Token Symbol**
EXE2

**Token Name**
EXEES2

**Token Logo**
![0x35c59bf2aa7ecb5a57fb011a4e763da6bae61445](https://user-images.githubusercontent.com/59862029/108971701-28c3a280-76b5-11eb-914f-0a17d5dcb5f8.png)

**Token Description**
A token that is used to utilize the products of EcoProtech.World

**Website**
https://ecoprotech.world

**Social links**
mailto: info@ecoprotech.world

**Comment by khaihkd** [comment]
duplicate #186
