### ISSUE TITLE
EGW LP Token Information Update

### ISSUE THREAD

**Issue by indiaprivate** [tomochain/tokens#185]
**Token Address**
e.g: https://scan.tomochain.com/address/0x4e6b60e8f1cfc4d1df9f09dfba38c4ba18a4fd17

**Token Symbol**
EGWLP

**Token Name**
EGW LP Token

**Token Logo**
https://i.ibb.co/cY6jrfY/lp-token-256.png

**Token Description**
EGW LP Token is for the liquidity providers who wish to provide liquidity to EGW tokens listed on LuaSwap. EGW LP Token manages the liquidity for the liquidity provider without the need for any technical knowledge. The EGW LP Token holder receives a fixed amount of EGW coins every month.

**Website**
https://www.egwcapital.com

**Social links**
https://twitter.com/egwcapital

**Comment by khaihkd** [comment]
done
