### ISSUE TITLE
Token Logo does not show up

### ISSUE THREAD

**Issue by SonTruongSG** [tomochain/tokens#186]
**Token Address**
https://scan.tomochain.com/address/0x35c59bf2aa7ecb5a57fb011a4e763da6bae61445

**Token Symbol**
EXE2

**Token Name**
EXEES2

**Token Logo**
PNG 256px by 256px: https://drive.google.com/file/d/1-JZrW1poN9wOMDc7ug_0kZ-egoNWgycI/view?usp=sharing

**Token Description**

**Website**
https://ecoprotech.world

**Social links**

**Comment by khaihkd** [comment]
done
