### ISSUE TITLE
MLR

### ISSUE THREAD

**Issue by MegaltrLottery** [tomochain/tokens#194]
**Token Address**
https://scan.tomochain.com/tokens/0x5080781e91237b6d7f026d5306b7233e26cd6c16

**Token Symbol**
MLR

**Token Name**
Mega Lottery

**Token Logo**
https://drive.google.com/file/d/1T4-0JaSa1K6SUJjmE9DkiFYXcdRmNE-u/view?usp=sharing

**Token Description**
MLR Token TRC21 is used to pay ticket and rewards of  Megamillions & Powerball US lottery at MegaLTR.com
It applies blockchain technology to buy tickets and receive rewards via smart contracts.
**Website**
https://megaltr.com

**Social links**
https://github.com/MegaltrLottery, https://t.me/MegaLTR_Lottery, https://twitter.com/MegaLTR

**Comment by khaihkd** [comment]
done
