### ISSUE TITLE
Update information of Koipool token

### ISSUE THREAD

**Issue by infinity2infinity** [tomochain/tokens#199]
**Token Address**
https://scan.tomochain.com/address/0xec8a3dd63322c2c6543b36b383e5c4f6145b291d
**Token Symbol**
KOI
**Token Name**
Koipool
**Token Logo**
**Token Description**
Koi is used to distribute for winner of jackpot on koipool.
**Website**
https://koi.tomopool.com
**Social links**
telegram
https://t.me/koipool

**Comment by khaihkd** [comment]
updated
