### ISSUE TITLE
WebbaCoin Changes

### ISSUE THREAD

**Issue by WebbaLuca** [tomochain/tokens#217]
**Token Address**
https://scan.tomochain.com/tokens/0x54502fd92556e5e9839a629a5fffa8cc55ac4349

**Token Symbol**
WBC

**Token Name**
WebbaCoin

**Token Logo**
https://webba-creative.com/documents/logo%20WebbaCoin.png

![logo WebbaCoin](https://user-images.githubusercontent.com/81247068/112165970-8208ee00-8bef-11eb-9b37-e954254689ab.png)

**Token Description**
WebbaCoin is a token that follows the requirement of Webba products, it supports all our projects: WSS, WCH, WFTP...

**Website**
https://webba-creative.com/

**Social links**
https://twitter.com/Webbacreative

https://www.instagram.com/webba_creative/

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/4a7d20aa093b2a9fa2105e2d7c7f57ae088213bf
