### ISSUE TITLE
Arnak

### ISSUE THREAD

**Issue by hosseinkord1** [tomochain/tokens#219]
**Token Address**
e.g: https://issuer.tomochain.com/token/0x384d91b4c0fefb33d441a0daf500760dbe2bbc86

**Token Symbol**
e.g: TOMO, Arkx

**Token Name**
e.g: TomoChain, Arnak x

**Token Logo**
PNG 256px by 256px

**Token Description**
A clear and concise description of the token.

**Website**
Link to the website that will use the token.

**Social links**
e.g Github, telegram, twitter

**Comment by khaihkd** [comment]
no info
