### ISSUE TITLE
AP Token

### ISSUE THREAD

**Issue by adityaindra68** [tomochain/tokens#220]
Token Address
**https://scan.testnet.tomochain.com/tokens/0x131182311876f423c3710da0add6d58eec4df848**

Token Symbol
**APT**

Token Name
**AP Token**

Token Logo
**![0x131182311876f423c3710dA0add6D58Eec4dF848 png](https://user-images.githubusercontent.com/41598512/112630593-5f353e80-8e68-11eb-9f6a-95fccc7b4b63.png)**

Token Description
**Become a millionaire for everyone**

Website
**Under construction**

Social links
**https://twitter.com/Airdropplatinum**
**https://t.me/airdropsplatinum_official**
**https://t.me/airdropsplatinum_channel**

**Comment by khaihkd** [comment]
it is testnet version?
