### ISSUE TITLE
PUFFIN LITE

### ISSUE THREAD

**Issue by HyperDNA** [tomochain/tokens#222]
**Token Address**
e.g: https://scan.tomochain.com/tokens/0x38c9fa10403d6f6e0f61790653d8af5f67ad9fb6

**Token Symbol**
e.g: PLite

**Token Name**
e.g: PUFFIN LITE

**Token Logo**
https://drive.google.com/file/d/12pbzNMOVPVPvB7rfCjGdgxBY9GDdtn0E/view?usp=drivesdk

**Token Description**
PLite Will be go to make a social media apps . Where People Can Earn Plite Token By Like,Comment, And Post .
This Apps Will Be Lunched on November 2021 . This Apps Is now Under buildup . After Build The Apps will Be Go for test For 1 Month .
Then Apps Will be publish on playstore And Appstore

**Website**
https://puffinlite.com
**Social links**
e.g telegram : https://t.me/Puffinlite
Facebook: https://m.facebook.com/Puffinlite/
Youtube: https://youtube.com/c/PuffinLite
Twitter: https://twitter.com/puffinlite

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/2ef350996f7a390a885af97fdcab05a28e019d7b
