### ISSUE TITLE
MaHalaX

### ISSUE THREAD

**Issue by wemahalax** [tomochain/tokens#223]
**Token Address**
https://etherscan.io/token/0x07f5bfe5d4dda58a620e622ccc05bca607a61e33

**Token Symbol**
MHX

**Token Name**
MaHalaX

**Token Logo**
http://mahalax.co.za/mx_256.jpg

**Token Description**
FORUS has created an equity token MahalaX which is used to distribute the wealth created to its investors and users. Universal stakeholding is achieved through the distribution of MahalaX across the platform user groups. All FORUS Group entities distribute 20% of all their earnings back to MahalaX.

**Website**
https://mahalax.co.za

**Social links**
https://www.facebook.com/mahalaxza
https://twitter.com/MalahaX
https://www.linkedin.com/company/mahalax/

**Comment by khaihkd** [comment]
you have to create a wrap token for it 
see more detail https://www.youtube.com/watch?v=SQwDeL_EryA
