### ISSUE TITLE
EGW Capital (EGW) Token Information Update

### ISSUE THREAD

**Issue by indiaprivate** [tomochain/tokens#225]
**Token Address**
https://scan.tomochain.com/address/0xfe319da470c38525002b5664026198ccc0629ec3

**Token Symbol**
EGW

**Token Name**
EGW Capital

**Token Logo**
PNG 256px by 256px
https://i.ibb.co/N1gRjmk/egw-mock.png

**Token Description**
EGW Capital is a blockchain and traditional investment bank which facilitates crypto and stock exchange listings.

**Website**
https://www.egwcapital.com

**Social links**
https://twitter.com/egwcapital
https://twitter.com/rahulegw

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/b351d3875d4b80534f0b0a00d4fae342136ef9a9
