### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by microcashofficial** [tomochain/tokens#229]
**Token Address**
https://scan.tomochain.com/tokens/0x1dadf37ecdca3c0f01eb845780080ee07c4fe758

**Token Symbol**
WFROG

**Token Name**
WRAPPED CYFROG

**Token Logo**
![profile](https://user-images.githubusercontent.com/74554853/114275976-44ef8900-9a42-11eb-8112-ef77102d2e18.png)

**Token Description**
Cyfrog Paywall Token is your VIP Backstage Pass to the Economic Revolution

**Website**
https://www.cyfrog.cash/

**Social links**
telegram : https://t.me/cyfrog

**Comment by microcashofficial** [comment]
Wating...🙂

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/c4a13f6411b77c7ca779e0c7d8e216699875e8f9
