### ISSUE TITLE
SLSH

### ISSUE THREAD

**Issue by slashfinancial** [tomochain/tokens#238]
**Token Address**
e.g: https://scan.tomochain.com/address/0xc809a65564d151606f2c6e10d523be9b3a108765

**Token Symbol**
e.g: SLSH

**Token Name**
e.g: Slash

**Token Logo**
https://github.com/tomochain/tokens/blob/f17fd5d9305bfd0e81a6b398174b8af5e505c818/tokens/0xc809a65564d151606f2c6e10d523be9b3a108765.png

**Token Description**
This Token is based on TomoChain and will use in the reward system for user-generated content.

**Website**
https://slash.financial

**Social links**
https://t.me/slashfinancial
https://www.reddit.com/user/slashfinancial
https://medium.com/@slashfinancial
https://www.youtube.com/channel/UCIr5ouTwXGwn2iQvE0t4oYQ
https://twitter.com/SlashFinancial
https://www.facebook.com/SlashFinancial/
https://github.com/slashfinancial

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/pull/237
