### ISSUE TITLE
TAI Stable Coin

### ISSUE THREAD

**Issue by kuynguien** [tomochain/tokens#239]
**Token Address**
e.g: https://scan.tomochain.com/address/0x4d04315e6BABD038d15ea0E240A88B292d2Add41

**Token Symbol**
e.g: https://www.dropbox.com/s/0638awjfxhzbarp/TAI.png?dl=0

**Token Name**
e.g: TAI

**Token Logo**
png 256px by 256px

**Token Description**
TAI is a TRC-21 token acting as Stablecoin. Users generate TAI by depositing collateral assets into TomoFinance.

**Website**
https://tomo.finance/

**Social links**
https://twitter.com/TomoFinance

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/63131779dcc632c2b930133961d062b1603eaabc
