### ISSUE TITLE
TFI Token

### ISSUE THREAD

**Issue by kuynguien** [tomochain/tokens#240]
**Token Address**
https://scan.tomochain.com/address/0x68691ffE88F794BBdCfD5b4Fd9DDEa2Bae33a008

**Token Symbol**
https://www.dropbox.com/s/ly643zk4h0as7m8/256x256.png?dl=0

**Token Name**
TFI

**Token Logo**
png 256px by 256px

**Token Description**
TFI is a TRC-21 token that will be rewarded to users whenever they Payback TAI, partly or entirely

**Website**
https://tomo.finance/

**Social links**
https://twitter.com/TomoFinance

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/commit/63131779dcc632c2b930133961d062b1603eaabc
