### ISSUE TITLE
Requiero Ayuda en Tomolssuer

### ISSUE THREAD

**Issue by joaquinales** [tomochain/tokens#283]
Hi friends
I have problems in Tomolssuer.
I cannot cancel the fee to proceed with the transactions.
https://issuer.tomochain.com/donateTxFee
I want to buy the Tomo but I have TRC21 Tokens And the platform requires me to be TOMO..
Thank you very much for your attention and I hope you can help me

**Comment by khaihkd** [comment]
You can buy TOMO from Binance or Kucoin and withdraw to your wallet
