### ISSUE TITLE
Update Airdrops Platinum Information

### ISSUE THREAD

**Issue by adityaindra68** [tomochain/tokens#287]
**Token Address**
https://scan.tomochain.com/tokens/0xe6a7bf45333a7018f709760263b7a5200d245ed3

**Token Symbol**
APT

**Token Name**
Airdrops Platinum

**Token Logo**
![AIRDROPS PLATINUM LOGO](https://user-images.githubusercontent.com/41598512/119245689-57aebf00-bba5-11eb-9a3a-2ad35f3dbf7c.png)

**Token Description**
Airdrops Platinum is the main gateway platform for projects and startups that will transform into a blockchain system with the full support of the worldwide community. Our vision is to create jobs for every people without income restrictions by participating in product development, blockchain projects and advertisers event.

**Website**
Under construction

**Social links**
- https://t.me/airdropsplatinum_channel
- https://t.me/airdropsplatinum_official
- https://t.me/airdropsplatinum_news
- https://twitter.com/Airdropplatinum
- https://www.youtube.com/channel/UC6WA1mWOZtV9WhCmHrGxYxQ
- https://www.linkedin.com/groups/13973476/
- https://medium.com/@airdropsplatinum

**Comment by khaihkd** [comment]
done

**Comment by adityaindra68** [comment]
We need to update token logo size.
