### ISSUE TITLE
Update token logo size, description and website address

### ISSUE THREAD

**Issue by adityaindra68** [tomochain/tokens#292]
**Token Address**
https://scan.tomochain.com/tokens/0xe6a7bf45333a7018f709760263b7a5200d245ed3

**Token Symbol**
APT

**Token Name**
Airdrops Platinum

**Token Logo**
![APT LOGO](https://user-images.githubusercontent.com/41598512/119320225-8f9d2b80-bca5-11eb-9f40-e40bb4a6750c.png)

**Token Description**
Airdrops Platinum is the premier platform for the transformation of conventional projects and startups into a blockchain system that is fully supported by the worldwide cryptocurrency community. Airdrops Platinum exists to create the world's largest blockchain ecosystem to create vast job opportunities for everyone without income restriction by participating in project development, blockchain startups and advertiser events.

**Website**
https://www.airdropsplatinum.com

**Social links**
- https://t.me/airdropsplatinum_channel
- https://t.me/airdropsplatinum_official
- https://t.me/airdropsplatinum_news
- https://twitter.com/Airdropplatinum 
https://www.youtube.com/channel/UC6WA1mWOZtV9WhCmHrGxYxQ
- https://www.linkedin.com/groups/13973476/
- https://medium.com/@airdropsplatinum

**Comment by khaihkd** [comment]
done
