### ISSUE TITLE
Update token logo

### ISSUE THREAD

**Issue by alijoei2** [tomochain/tokens#293]
**Token Address**
https://scan.tomochain.com/address/0x021d8b9647c9d19fb865931461eb85b6b4013e79

**Token Symbol**
IRAN

**Token Name**
IRAN

**Token Logo**
https://i.pinimg.com/originals/0b/eb/3b/0beb3b80ae3e5622db92f6ea21ea8b50.png

**Token Description**

**Website**

**Social links**

**Comment by khaihkd** [comment]
added logo
