### ISSUE TITLE
Update Token Information

### ISSUE THREAD

**Issue by alijoei2** [tomochain/tokens#294]
**Token Address**
https://scan.tomochain.com/address/0x7769257a32ca959d717c06a3978c2213ba289025

**Token Symbol**
ALI

**Token Name**
Ali

**Token Logo**
https://i.pinimg.com/originals/50/c1/9a/50c19af53240b37663d712a0d55416fd.png

**Token Description**
Tʜɪɴᴋ ʙɪɢ, ʙᴇʟɪᴇᴠᴇ ʙɪɢ, ᴀᴄᴛ ʙɪɢ, ᴀɴᴅ ᴛʜᴇ ʀᴇsᴜʟᴛs ᴡɪʟʟ ʙᴇ ʙɪɢ

**Website**
https://alijoei.ir/

**Social links**
https://twitter.com/Ali_Joei
https://t.me/alijoei_Token

**Comment by khaihkd** [comment]
updated
