### ISSUE TITLE
Update Token Info

### ISSUE THREAD

**Issue by SharkChain** [tomochain/tokens#301]
**Token Address**
e.g: https://scan.tomochain.com/address/0x8865280c31B8CBC7b96cE48Ad52C122E6D82806a

**Token Symbol** SHARK

**Token Name** SharkToshi

**Token Logo**
![circle-cropped (1)](https://user-images.githubusercontent.com/85309903/121172498-67045c80-c875-11eb-8dac-5833b3c3d408.png)

**Token Description**
Shark's Don't Swim Backwards

**Website**
https://sharktoshi.com/

**Social links**
https://twitter.com/ToshiSharks
https://t.me/ToshiShark
https://t.me/sharkToshi

**Comment by SharkChain** [comment]
I request you to please update it as soon as possible , 

Thanks 
SharksToshi

**Comment by SharkChain** [comment]
Hello Do Minh Khai and Nguyen Sy Thanh Son please update our token info as soon as possible 

Thanks

**Comment by SharkChain** [comment]
Hello Its the first day of the next month as you have mentioned to update the token information , please do reply if there is any problem we can update that

**Comment by khaihkd** [comment]
done
