### ISSUE TITLE
Made by Ra's al Ghul League

### ISSUE THREAD

**Issue by Trolltrolling** [tomochain/tokens#311]
**Token Address**
e.g: https://scan.tomochain.com/address/0x

**Token Symbol**
e.g: TOMO, UFO

**Token Name**
e.g: TomoChain, UFO Ianau

**Token Logo**
PNG 256px by 256px
https://ufoinu.com/coin_logo/ufo_icon.png
**Token Description**
A clear and concise description of the token.
We will use a kind of artificial intelligence technology beyond the comprehensiveness of today humanity.
**Website**
Link to the website that will use the token.
http://ufoinu.com/
**Social links**
e.g Github, telegram, twitter
http://ufoinu.com/

**Comment by khaihkd** [comment]
#312
