### ISSUE TITLE
Made by Ra's al Ghul League

### ISSUE THREAD

**Issue by Trolltrolling** [tomochain/tokens#312]
**Token Address**
e.g: https://scan.tomochain.com/address/0xd667b976e83de476a8d16116fb0c9e7eba8dd772

**Token Symbol**
e.g: TOMO, UFO

**Token Name**
e.g: TomoChain, UFO INU

**Token Logo**
http://ufoinu.com/coin_logo/256X256.png

**Token Description**
We will use a kind of artificial intelligence technology beyond the comprehensiveness of today humanity.

**Website**
http://ufoinu.com/

**Social links**
e.g Github, https://t.me/ufoinucoin, https://twitter.com/InuUfo

**Comment by Trolltrolling** [comment]
Made by Ra's al Ghul League

**Comment by khaihkd** [comment]
updated
