### ISSUE TITLE
Update official website Airdrops Platinum

### ISSUE THREAD

**Issue by adityaindra68** [tomochain/tokens#316]
**Token Address**
https://scan.tomochain.com/tokens/0xe6a7bf45333a7018f709760263b7a5200d245ed3

**Token Symbol**
APT

**Token Name**
Airdrops Platinum

**Website**
https://airdropsplatinum.com/

**Comment by adityaindra68** [comment]
We need to update our official website, thanks

**Comment by khaihkd** [comment]
updated
