### ISSUE TITLE
Onlinetravelagent

### ISSUE THREAD

**Issue by Onlinetravelagent** [tomochain/tokens#322]
Token Address
https://scan.tomochain.com/tokens/0xd1eed628023839521a4fd79a6fd96fe5740101c1
Token Symbol
OTA

Token Name
Online Travel Agent

Token Logo
https://drive.google.com/file/d/1m8ENOQazP5V1ohwdIx7-NAohHxfxXjFo/view?usp=sharing

Token Description
OTA Token TRC21 can buy  More than 2,000,000 travel products worldwide and can be payment with OTA Cryptocurrency . it is available in many  languages and will having offer more  millions reported accommodation listings, including over homes, apartments, and other unique places to stay. Wherever you want to go and whatever you want to do. Onlinetravelasia.com makes it easy and supports you with 24/7 customer support..
Website
https://onlinetravelasia.com

Social links
https://github.com/Onlinetravelagent, https://t.me/onlinetravelagent1, https://twitter.com/OnlineTravelAg2, https://www.facebook.com/onlinetravelasia

**Comment by khaihkd** [comment]
done

**Comment by Onlinetravelagent** [comment]
thanks so much
