### ISSUE TITLE
EcpExchange

### ISSUE THREAD

**Issue by EcpExchange** [tomochain/tokens#324]
**Token Address**
https://scan.tomochain.com/tokens/0x5650ea7e65057b68d59fb5a62be25adf94c805bf

**Token Symbol**
ECP

**Token Name**
Ecommerce platform

**Token Logo**
https://drive.google.com/file/d/1YRQqmHByp4J4xVuhN52gR7K_aa23OILl/view?usp=sharing

**Token Description**
ECP.exchange is an e-commerce platform where buyers and sellers exchange directly with each other without intermediaries.
ECP(Token TRC21) is used as a means of payment at ECP.exchange

**Website**
https://ecp.exchange

**Social links**
https://github.com/EcpExchange,https://t.me/ecpexchange,https://twitter.com/EcpExchange,https://www.facebook.com/groups/ecpexchange,https://www.facebook.com/ECPTRC21,http://www.tiktok.com/@ecpexchange,https://www.youtube.com/channel/UCZDn-Hsd2zX-X5eoUdR0PTQ

**Comment by donaldtrumpvu** [comment]
Great project :dancing_men:

**Comment by khaihkd** [comment]
website is not working
