### ISSUE TITLE
TABANK

### ISSUE THREAD

**Issue by cryptorbank** [tomochain/tokens#325]
Token Address
https://scan.tomochain.com/tokens/0x8103bb77ed2035b5da9a3a65d9c313cb6ee41dbd

Token Symbol
TAB

Token Name
TAB BANK

Token Logo
https://drive.google.com/file/d/1Eze8uDBelmryKOIzPh2fBR96w7t_FT40/view?usp=sharing

Token Description
crypto ecosystem that include: e-commerce, social networks, exchanges and crypto wallet

Website
https://tabank.org

Social links
https://t.me/tabankorg
https://twitter.com/OrgTabank

**Comment by khaihkd** [comment]
done
