### ISSUE TITLE
assistance request publish of contract

### ISSUE THREAD

**Issue by busytoby** [tomochain/tokens#33]
I have some difficulty publishing a sale standard TRC21 token contract for my token after addition to the repository.

I received the link https://scan.testnet.tomochain.com/contracts/verify?address=0x[removed]
But i do not recognize the address in 0x[removed] as being related to my token?

The token was created with address 0xa10622c7f7847c5e9f592f068b068d52e334bf2e as added to the repository different from 0x[removed] address above.

I have tried copying example Solidity code from other basic non-mintable tokens but it shows in all cases that the code is not verifiable.

My questions follow:
1. Is there some example of basic contract for non-mintable token to be submitted via this interface?  
2. What is the function of 0x[removed] address above provided in the link from dev to add my token contract?

**Comment by thanhson1085** [comment]
Contact @khaihkd in telegram for the support.
