### ISSUE TITLE
Ecp

### ISSUE THREAD

**Issue by EcpExchange** [tomochain/tokens#330]
**Token Address**
https://scan.tomochain.com/tokens/0x5650ea7e65057b68d59fb5a62be25adf94c805bf

**Token Symbol**
ECP

**Token Name**
Ecommerce platform

**Token Logo**
https://drive.google.com/file/d/1g1_pYa_0rWZW6SOBjTI1S-QzEnlxrclL/view?usp=sharing

**Token Description**
ECP is a TRC21 token used as a means of payment at https://ecp.exchange
https://ecp.exchange is an e-commerce platform where buyers and sellers exchange directly with each other without intermediaries

**Website**
https://ecp.exchange

**Social links**
https://github.com/EcpExchange,https://t.me/ecpexchange,https://twitter.com/EcpExchange,https://www.facebook.com/groups/ecptokentrc21

**Comment by EcpExchange** [comment]
Please approve Github
Thank you so much

**Comment by EcpExchange** [comment]
Please approve Github soon
Thank you so much

**Comment by EcpExchange** [comment]
When is it approved?

**Comment by EcpExchange** [comment]
Please approve Github
Thank you so much

**Comment by EcpExchange** [comment]
When is it approved?

**Comment by EcpExchange** [comment]
Please approve Github

**Comment by khaihkd** [comment]
We change the rule because so many spam token request update info. Please read more in here https://github.com/tomochain/tokens

**Comment by EcpExchange** [comment]
Do I need to contribute 20 or 30 tomo to this smart contract address correct?

**Comment by EcpExchange** [comment]
Do I need to contribute 20 or 30 tomo to this smart contract address
correct?

Vào Th 7, 21 thg 8, 2021 vào lúc 09:22 Do Minh Khai <
***@***.***> đã viết:

**Comment by EcpExchange** [comment]
I sent 20 TOMO
Please approve the update for ECP: https://scan.tomochain.com/tokens/0x5650ea7e65057b68d59fb5a62be25adf94c805bf

sent 20 Tomo
https://scan.tomochain.com/txs/0xdb6ca8d221a25e19665993b7e713b649705f80e0117e47c7f693ba0d578d3d3c

**Comment by EcpExchange** [comment]
I sent 20 TOMO
Please approve the update for ECP:
https://scan.tomochain.com/tokens/0x5650ea7e65057b68d59fb5a62be25adf94c805bf

sent 20 Tomo
https://scan.tomochain.com/txs/0xdb6ca8d221a25e19665993b7e713b649705f80e0117e47c7f693ba0d578d3d3c

Thank you so much

Vào Th 2, 23 thg 8, 2021 vào lúc 14:53 Exchange ECP <
***@***.***> đã viết:

**Comment by khaihkd** [comment]
merge
