### ISSUE TITLE
purnhub

### ISSUE THREAD

**Issue by moeinndn** [tomochain/tokens#332]
**Token Address**
https://scan.tomochain.com/address/0x3fbDbaE5612Ae7c0FdBfecAcD25A4E9dcD441BD7

**Token Symbol**
HUB

**Token Name**
Purn Hub

**Token Logo**
https://drive.google.com/file/d/1-2HVxS_ELjTxXHIAu-p56XsWKHxNe7aq/view?usp=drivesdk

**Token Description**
The best token of tomochain

**Website**
www.purnhub.com
**Social links**
@TiTANiC_Ads, @AmACoin2

**Comment by ProfSoumya** [comment]
I guess the format is incorrect it should be in .json. not just plain text .lets hope admin can guide u better

**Comment by khaihkd** [comment]
Closed because we still not received payment info. You can read rule in README.MD. after that you can re-open this ticket
