### ISSUE TITLE
CINFO token

### ISSUE THREAD

**Issue by cinfoco** [tomochain/tokens#336]
**Token Address**
https://scan.tomochain.com/address/0x543c41ec78755bf9bf7dab86f247b4e91ce42239

**Token Symbol**
CINFO

**Token Name**
Capital Info 

**Token Logo**
![0x543c41ec78755bf9bf7dab86f247b4e91ce42239](https://user-images.githubusercontent.com/88945990/129458844-debf90e0-8755-44db-820f-f11c32c61698.png)

**Token Description**
Provide news and investment information

**Website**
https://capitalinfo.org/

**Social links**
        "telegram": "https://t.me/cinfo_ir",
        "twitter": "https://twitter.com/cinfo_ir",
        "instagram": "https://www.instagram.com/cinfo_ir"

**Comment by khaihkd** [comment]
Closed because we still not received payment info. You can read rule in README.MD. after that you can re-open this ticket
