### ISSUE TITLE
MY IDENTITY Coin

### ISSUE THREAD

**Issue by hkim77761** [tomochain/tokens#339]
**Token Address**
https://scan.tomochain.com/address/0xd9625fd459693dd012366a207355dfd2ffc461c2

**Token Symbol**
MYID

**Token Name**
MY IDENTITY Coin

**Token Logo**
PNG 256px by 256px

![Icon-01 (1) (4)](https://user-images.githubusercontent.com/58203347/132962592-f4da1c67-dde2-4902-a7a2-a1649139bf10.png)

**Token Description**
MY IDENTITY Coin (MYID) is a utility token used for tagging of cryptographic blocks with unique owner identifying code with proprietary Proof of Person (POP) technology.   The purpose of tagging blockchains with MYID coin coding is to reduce and ultimately eliminate threat of loss, theft or unfair confiscation.

**Website**
www.okglobalcoinsg.com

**Social links**

WEBSITE: https://okglobalcoinsg.com 
TELEGRAM: https://t.me/myidentitycoin
FACEBOOK: https://www.facebook.com/Myidentitycoin
TWITTER: https://twitter.com/MyIdentityCoin
INSTAGRAM: https://www.instagram.com/myidentitycoin
TIKTOK: https://vt.tiktok.com/ZSJmB4N8y

**Comment by hkim77761** [comment]
Please add the logo to the tomobridge option.  Our MYID Coin was added a week ago but we would like our logo included please.  Thank you.

**Comment by hkim77761** [comment]
Please also add the logo to the tomowallet.  Thank you.

**Comment by hkim77761** [comment]
Hello...Can somebody please help?  There has been no status update.  Thank you.

**Comment by khaihkd** [comment]
@hkim77761 please read README.MD again

**Comment by khaihkd** [comment]
Closed because we still not received payment info. You can read rule in README.MD. after that you can re-open this ticket

**Comment by hkim77761** [comment]
Hello...I just sent in payment.  Can you please make the coin edits requested?   Thank you.
