### ISSUE TITLE
MY IDENTITY Coin logo update on bridge and wallet

### ISSUE THREAD

**Issue by hkim77761** [tomochain/tokens#340]
**Token Address**
https://scan.tomochain.com/address/0xd9625fd459693dd012366a207355dfd2ffc461c2

**Token Symbol**
MYID

**Token Name**
MY IDENTITY Coin

**Token Logo**

![Icon-01 (1) (4)](https://user-images.githubusercontent.com/58203347/134215272-543c28a6-7983-4646-b0ae-ee30086b532b.png)

**Token Description**
MY IDENTITY Coin (MYID) is a proprietary Proof of Person(POP) technology used for the optional tagging of blockchain assets with unique owner identifying code. The purpose of tagging blockchains with MYID coin coding is to reduce and ultimately eliminate threat of loss, theft or unfair confiscation.

**Website**
https://www.okglobalcoinsg.com

**Social links**
TELEGRAM: https://t.me/myidentitycoin
FACEBOOK: https://www.facebook.com/Myidentitycoin
TWITTER: https://twitter.com/MyIdentityCoin
INSTAGRAM: https://www.instagram.com/myidentitycoin
TIKTOK: https://vt.tiktok.com/ZSJmB4N8y

**Comment by hkim77761** [comment]
![payment to tomo](https://user-images.githubusercontent.com/58203347/134215877-ded43ab4-6ea9-4d25-92ae-16222a167bc5.png)


Please update the logo on tomobridge and tomowallet.  Thank you.

**Comment by hkim77761** [comment]
Hello....the status please?  thank you.

**Comment by khaihkd** [comment]
@hkim77761 Logo need is a square. Update your website is https

**Comment by hkim77761** [comment]
> @hkim77761 Logo need is a square. Update your website is https

The logo needs to be a square in tomowallet also???  We would like the tomobridge to show our icon and the tomowallet.

**Comment by hkim77761** [comment]
![square icon for tomobridge](https://user-images.githubusercontent.com/58203347/134961440-fdcf5ee4-540b-4eb0-8cb3-50f1fc1355ee.png)

**Comment by hkim77761** [comment]
the icon I just sent is square but with a transparent border.  Will this suffice?  Thank you.

**Comment by hkim77761** [comment]
The website address was also edited to an https.

**Comment by khaihkd** [comment]
updated
