### ISSUE TITLE
EVND token verification information

### ISSUE THREAD

**Issue by EVND** [tomochain/tokens#38]
**Token Symbol** EVND
e.g: TOMO, KNC

**Token Name** Viet Nam Dong
e.g: TomoChain, Kyber

**Token Logo** 
![EVND](https://user-images.githubusercontent.com/61536046/75427188-993bc480-5978-11ea-971f-f4e23d2bfb72.png)

PNG 256px by 256px

**Token Description** :  EVND token information. This is a Fiat token developed on the TRC21 blockchain platform of TOMO Chain.EVND is used to pay for consumer shopping bills through EVND Wallet payment application

**Website**
https://datacoinex.io

**Social links**  : https://github.com/EVND
e.g Github, telegram, twitter

**Comment by thanhson1085** [comment]
@khaihkd please help this case.
Token address is: https://scan.tomochain.com/tokens/0x053bb94fb2b1bfc2a1a7f964068b22516cb6fe45

**Comment by khaihkd** [comment]
https://github.com/tomochain/tokens/pull/39
