### ISSUE TITLE
Update Token Logo (POMO)

### ISSUE THREAD

**Issue by PomodoroToken** [tomochain/tokens#43]
Please update the Token Logo for POMO

Contract: 0x31e58cca9ecaa057edabaccff5abfbbc3443480c

![0x31e58cca9ecaa057edabaccff5abfbbc3443480c png](https://user-images.githubusercontent.com/56785480/75656255-7b61ae80-5c5b-11ea-9313-cdd258a41409.png)

**Comment by thanhson1085** [comment]
Fixed https://github.com/tomochain/tokens/commit/365899b083def81a4474cbd9fa2627b4bb48b564
