### ISSUE TITLE
Update Token Logo (POMO)

### ISSUE THREAD

**Issue by PomodoroToken** [tomochain/tokens#44]
Token Address: 0x31e58ccA9ecaA057eDABACCFf5ABFbbC3443480C

![0x31e58cca9ecaa057edabaccff5abfbbc3443480c](https://user-images.githubusercontent.com/56785480/75672196-22544380-5c78-11ea-84d9-c4fc9e9d9e9b.png)

**Comment by thanhson1085** [comment]
Fixed https://github.com/tomochain/tokens/commit/8730a294399c4bc46680fde655c417e3453da950
