### ISSUE TITLE
CryptotipsFriends Update

### ISSUE THREAD

**Issue by cryptotipsfriends** [tomochain/tokens#47]
**Token Address**
https://scan.tomochain.com/address/0x59efb1239922367f199036afc272f54f79f10ce6

**Token Symbol**
CP88

**Token Name**
Cryptotipsfriends

**Token Logo**
PNG 256px by 256px

**Token Description**
Community Token 

**Website**
Cryptotipsfriends.com 

**Social links**
https://t.me/Cryptotipsfr
https://t.me/CryptotipschatFR
https://twitter.com/cryptotipsfr/

**Comment by khaihkd** [comment]
Wrong token address. this is normal address
no logo found.

@cryptotipsfriends Please update

**Comment by thanhson1085** [comment]
Closed, feel free to open when you have the answer
