### ISSUE TITLE
IDR Private (IDRP)

### ISSUE THREAD

**Issue by RakaWA** [tomochain/tokens#52]
**Token Address**
https://scan.tomochain.com/address/0xc28194b773ce7b4d74c87e551afe991bd49a1d4e

**Token Symbol**
IDRP

**Token Name**
IDR Private

**Token Logo**
[Link Image](https://drive.google.com/file/d/1zAJgMiyBtS5_8HFUuWGHBePFBI9FOjMc/view?usp=sharing)

**Token Description**
IDR Private is issued by PT Rupiah Digital Indonesia, a legal company in Republic of Indonesia. IDR Private (IDRP) is a smart service using blockchain technology for asset security. The assets guarantor of IDRP is the government-appointed Margin Depositing Bank.

**Website**
https://idrp.io/

**Social links**
https://github.com/IDR-Private
https://www.instagram.com/idrp.io/
https://www.linkedin.com/company/pt-rupiah-digital-indonesia/

**Comment by thanhson1085** [comment]
@khaihkd take a look this issue.

**Comment by thanhson1085** [comment]
Merged.
