### ISSUE TITLE
Please update logo (LARB)

### ISSUE THREAD

**Issue by larbofficial** [tomochain/tokens#54]
Token Address
https://scan.tomochain.com/address/0x3a5F05396D310DCfBfF1B1bD7BC8746D727e384E

**Token Symbol**
LARB

**Token Name**
LARB

**Token Logo**

![logo](https://user-images.githubusercontent.com/64442862/80509283-1c759880-8971-11ea-9fce-06a5e484c212.png)

**Comment by khaihkd** [comment]
do you have extra info (website or social network) @larbofficial

**Comment by larbofficial** [comment]
Yes, it will be updated next week @khaihkd

**Comment by larbofficial** [comment]
Official website 
Https://inlarb.com 

Twitter
Twitter.com/inlarb
@khaihkd @thanhson1085
