### ISSUE TITLE
Logo & contract address

### ISSUE THREAD

**Issue by Munguajuna** [tomochain/tokens#55]
Hello!
Can't add a token logo
and
Can't verify and publish the contract address

**Comment by Munguajuna** [comment]
The token name is SAFARI
Symbol: SFR
Contract address: 0xf453d36acde1781a19acd7ae0fcc86a8cc998a8a

**Comment by khaihkd** [comment]
Please upload you token logo and source code contract at this issue
@Munguajuna

**Comment by Munguajuna** [comment]
I don't see the source code? Where can I find it?
Logo👇

**Comment by Munguajuna** [comment]
![Logopit_1588418178706](https://user-images.githubusercontent.com/43640722/80915389-bc109d80-8d5a-11ea-92e7-9fb4ab9490b0.png)

**Comment by Munguajuna** [comment]
I can't find the source code for the contract address??

**Comment by khaihkd** [comment]
Image Requirements

file extension: png. Uppercase PNG considered invalid.
name：contract_address.png in lowercase register. Ex: 0xea8d13af16a33fc5de19c0b1edcf4cd053bd2fa9.png
size: 256px by 256px
background: preferably transparent
use simple drag and drop online service tinypng to optimize image size

Did you use TomoIssuer? If correct dont need source code

**Comment by thanhson1085** [comment]
Closed, fee free to open when you have the answer
