### ISSUE TITLE
UPLoad INformation Of My coin 

### ISSUE THREAD

**Issue by RSCOIN2020** [tomochain/tokens#62]
**Token Address**
https://scan.tomochain.com/address/0xc7f08a11f571b38a402d77bc1e5a097d3561f239

**Token Symbol**
RSCOIN, RSC

**Token Name**
 Rscoin 

**Token Logo**
![RSCOINRSC](https://user-images.githubusercontent.com/65510919/82204716-d2a02280-991e-11ea-8011-f70e0180d36a.png)

**Token Description**
RSCOIN is an open source, global payment network that is fully decentralized without any central authorities. Mathematics secures the network and empowers individuals to control their own finances. With substantial industry support, trade volume and liquidity,

**Website**
Coming Soon 

**Social links**
Github::https://github.com/RSCOIN2020
Twitter::https://twitter.com/RSCOIN1
Telegram::https://t.me/RSCOIN1

**Comment by thanhson1085** [comment]
@khaihkd support this case, thanks

**Comment by thanhson1085** [comment]
done
