### ISSUE TITLE
update Larb token Logo

### ISSUE THREAD

**Issue by larbofficial** [tomochain/tokens#64]
**Token Address**
e.g: https://scan.tomochain.com/address/0x3a5F05396D310DCfBfF1B1bD7BC8746D727e384E

**Token Symbol**
LARB

**Token Name**
Larb

**Token Logo**
PNG 256px by 256px

**Token Description**
inLarb native asset backed utility token.

**Website**
https://inlarb.com.

**Social links**
Telegram - https://t.me/inlarbnetwork
Twitter - https;//twitter.com/inlarb
Instagram - https://instagram.com/inlarbnetwork
Youtube - https://www.youtube.com/channel/UCCDn7l-MXhfprWb44yXc4jw

![emblem](https://user-images.githubusercontent.com/64442862/83080135-5ec7ed80-a075-11ea-99c5-440e5470ac47.png)

**Comment by thanhson1085** [comment]
Done https://github.com/tomochain/tokens/pull/67
