### ISSUE TITLE
Request for Updating Token Information: PantoDraw

### ISSUE THREAD

**Issue by phucdt1713** [tomochain/tokens#65]
**Token Address**
https://scan.tomochain.com/address/0xe6a3017ebf0cde62a29640d557e9b440a6aa4fe9

**Token Symbol**
TICKET

**Token Name**
PantoDraw

**Token Logo**
![0xE6A3017ebF0CDE62a29640D557E9B440A6Aa4FE9](https://user-images.githubusercontent.com/59862029/83617641-907c0f80-a5b3-11ea-8c58-3850dc21052f.png)

**Token Description**
A token that is used to play PantoDraw Gacha.

**Website**
https://pantograph.io/

**Social links**
Email: pantograph@bacoor.co
Facebook: https://www.facebook.com/Pantograph.io
Twitter: https://twitter.com/pantograph_io
Telegram: https://t.me/pantograph_io
Instagram: https://instagram.com/pantograph_io
Reddit: https://www.reddit.com/r/Pantograph

**Comment by thanhson1085** [comment]
Done https://github.com/tomochain/tokens/pull/67
