### ISSUE TITLE
Request for Updating Safari Token Info on TomoScan

### ISSUE THREAD

**Issue by Munguajuna** [tomochain/tokens#66]
**Token Address**
https://scan.tomochain.com/address/0xf453D36aCDe1781a19aCd7Ae0fCc86a8cc998a8A

**Token Symbol**
SFR

**Token Name**
SAFARI

**Token Logo**
![Logopit_1588418178706](https://user-images.githubusercontent.com/43640722/83943992-00370800-a809-11ea-8e4c-0c8cb26c3e17.png)

**Token Description**
Safari proposes an ecosystem designed to change the way clients looking for consultancy services perform their sourcing 
and help consultants to advertise and drive customers to their businesss. The Safari ecosystem include: 
✓SFR token: The Safari Token (SFR) will be used to power the payment system on mobile application for consultancy services sourcing platform & SafariDEX.  

✓Clients: Providing clients/customers looking for consultancy services access to consultant's profile, local trends, promotions and deals based on their current or any location. Enabling clients to become aware of profile, social  
media posts, offers and trends from consultancy services providers around them. 

✓Consultants: Affordable and more effective advertising platform, enabling them 
to target nearby clients with incentives to visit their offices or close the deal through our platform. 

**Website**
https://medium.com/@safaritoken

**Social links**
Telegram: https://t.me/safari_official
Twitter: https://twitter.com/SafariOfficial1?s=09

**Comment by khaihkd** [comment]
@Munguajuna please use correct logo size (256x256px), your logo size is too large (720x720px)

**Comment by Munguajuna** [comment]
Here is the required logo

**Comment by Munguajuna** [comment]
Here's the required logo
![Safari Token (SFR) 256](https://user-images.githubusercontent.com/43640722/83995435-173d3d80-a962-11ea-80d3-905d242f2c23.png)

**Comment by Munguajuna** [comment]
💪
