### ISSUE TITLE
0x64Dc65AEe1dE6164E78996a5879c3726CBE5D6f1

### ISSUE THREAD

**Issue by KANZEN-KZN** [tomochain/tokens#72]
**Token Address**
https://scan.tomochain.com/address/0x64dc65aee1de6164e78996a5879c3726cbe5d6f1

**Token Symbol**
KZN

**Token Name**
KANZEN

**Token Logo**
![0x64Dc65AEe1dE6164E78996a5879c3726CBE5D6f1](https://user-images.githubusercontent.com/67109271/85034791-050a9d00-b1b5-11ea-9e45-e9fcd5767e67.png)

**Token Description**
Kanzen is a peer-to-peer Internet currency that enables instant, near-zero cost payments to anyone in the world. 

**Website**
https://kzen.online/

**Social links**
https://www.facebook.com/kanzen.tomo.9
https://twitter.com/KANZENTOMO?s=09
https://www.instagram.com/kanzentomo/
https://t.me/Kanzentomo
https://github.com/KANZEN-KZN

**Comment by thanhson1085** [comment]
Done

**Comment by KANZEN-KZN** [comment]
> Done

Thank you very much.
Who I should contact for "Verify and Publish Contract" in Tomoscan.
