### ISSUE TITLE
OkGlobal Coin USA logo upload request

### ISSUE THREAD

**Issue by hsk77761** [tomochain/tokens#75]
**Token Address**
https://scan.tomochain.com/address/0x6806cf534e79b539d7945f4e09b235ca861cde7d

**Token Symbol**
OKGUS

**Token Name**
OkGlobal Coin USA

**Token Logo**
![okglobal logo 256x256](https://user-images.githubusercontent.com/66628084/85111945-dc40d280-b1c9-11ea-9815-924207015d94.png)

**Token Description**
Security coin issued by OkGlobal Coin USA

**Website**
www.okglobalcoin.com

**Social links**
e.g Github, telegram, twitter

**Comment by khaihkd** [comment]
@hsk77761 please update token info

**Comment by thanhson1085** [comment]
What is your Social links? @hsk77761

**Comment by hsk77761** [comment]
Hello,


 We do not list any social links.  Thank you.


-------- Original message --------

**Comment by thanhson1085** [comment]
Done
