### ISSUE TITLE
SWITCH Coin logo upload request

### ISSUE THREAD

**Issue by hsk77761** [tomochain/tokens#76]
**Token Address**
https://scan.tomochain.com/address/0x905f67f5b0bae2615d332ee22a896f088b305d90

**Token Symbol**
SWTCH

**Token Name**
e.g: TomoChain, Kyber

**Token Logo**
![switch logo 256x256](https://user-images.githubusercontent.com/66628084/85112350-5a9d7480-b1ca-11ea-8691-ff61710e6543.png)

**Token Description**
Stable coin issued by OkGlobal Coin SWITCH Pte. Ltd.

**Website**
www.okglobalcoinsg.com

**Social links**
e.g Github, telegram, twitter

**Comment by khaihkd** [comment]
@hsk77761 you have to update all info

**Comment by thanhson1085** [comment]
What is your Token Name, and Social links? @hsk77761

**Comment by hsk77761** [comment]
SWITCH stable coin
No social links.


-------- Original message --------

**Comment by thanhson1085** [comment]
Done
