### ISSUE TITLE
Smart contract code

### ISSUE THREAD

**Issue by larbofficial** [tomochain/tokens#78]
When deploying smart contract using Tomoissuer, the code was not saved. Is there a way to get the code for verification and other use? TomoZ protocol applied.
Token Address
https://scan.tomochain.com/address/0x3a5F05396D310DCfBfF1B1bD7BC8746D727e384E

Token Symbol
LARB

Token Name
Larb

**Comment by thanhson1085** [comment]
Yep, we will support it by completing this issue https://github.com/tomochain/tomoissuer/issues/195

But @khaihkd can manually verify it for you

**Comment by thanhson1085** [comment]
Now you can view the source code in TomoIssuer https://github.com/tomochain/tomoissuer/pull/197
