### ISSUE TITLE
Update FLETA Token Information

### ISSUE THREAD

**Issue by judasowelu** [tomochain/tokens#79]
**Token Address**
https://scan.tomochain.com/tokens/0xa117ea1c0c85cef648df2b6f40e50bb5475c228d

**Token Symbol**
FLETA

**Token Name**
FletaToken

**Token Logo**
https://fleta.io/assets/images/fleta-token-symbol-256px.png

**Token Description**
The Platform for Sustainable DApp Ecosystem

**Website**
https://fleta.io/

**Social links**
Blog: https://medium.com/fleta-first-chain
Reddit: https://www.reddit.com/r/fletachain
Twitter: https://twitter.com/fletachain
Github: https://github.com/fletaio
Telegram: https://t.me/FLETAofficialGroup
Linkedin: https://www.linkedin.com/company/fleta
Kakaotalk: https://open.kakao.com/o/gDDjvgN
Discord: FLETA Developer Community
Email: hello@sendsquare.co
Whitepaper: https://fleta.io/download/FLETA_Buisness%20Whitepaper_EN.pdf
CoinMarketCap: https://coinmarketcap.com/currencies/fleta
CoinGecko: https://www.coingecko.com/en/coins/fleta

**Comment by thanhson1085** [comment]
Your token already issued on Ethereum, why do you want to move it to TomoChain?

**Comment by judasowelu** [comment]
FLETA has a gateway network to allow interoperability between protocols. We are issuing FLETA TRC-20 tokens to connect TomoChain network with FLETA nerwork. To allow our users to dive in TomoChain Ecosystem.

**Comment by thanhson1085** [comment]
Yep, you should use TRC21 standard that is easy be listing on TomoX DEXs

**Comment by judasowelu** [comment]
okay. We will call the stoptrade(). Then, issue TRC21 FLETA tokens

**Comment by judasowelu** [comment]
We issued TRC21 FLETA tokens and updated the token address infomation. 
Please update FLETA Token Information on tomoscan.

**Comment by thanhson1085** [comment]
Done
