### ISSUE TITLE
Update token info

### ISSUE THREAD

**Issue by larbofficial** [tomochain/tokens#80]
**Token Address**
e.g: https://scan.tomochain.com/address/0x15B3BEcf2527f23a5A3E510e99167dadC09AE28b

**Token Symbol**
LARB

**Token Name**
Larb

**Token Logo**
PNG 256px by 256px
![Larb_logo](https://user-images.githubusercontent.com/64442862/86453166-40f54480-bd15-11ea-9b28-712e32bd8731.png)

**Token Description**
inLarb Network native utility token.

**Website**
https://inlarb.com.

**Social links**
Telegram - https://t.me/inlarb_network
Twitter - https;//twitter.com/inlarb
Instagram - https://instagram.com/inlarbnetwork
Youtube - https://www.youtube.com/channel/UCCDn7l-MXhfprWb44yXc4jw

**Comment by khaihkd** [comment]
why did you create so many inLarb token? #54 & #64 what is about them?

**Comment by larbofficial** [comment]
#54 was non mintable token, we changed our tokenomics and had to burn 54 by
sending all token into a non existing address with no private key. #64 is a
mintable token which will be our main token. If it's possible to remove #54
from the blockchain entirely, we will be grateful.
In general, #54 was a mistake

**Comment by larbofficial** [comment]
hello @khaihkd nothing yet?

**Comment by khaihkd** [comment]
okey, I will remove 2 tokens info from #54 and #64

**Comment by larbofficial** [comment]
Yes, thanks

**Comment by thanhson1085** [comment]
Done

**Comment by larbofficial** [comment]
Hello @khaihkd @thanhson1085 is it possible for $Tomo deposited for TRC21 fee be sent back to wallet? I deposited some $tomo for #54 and would love to have them only wallet back

**Comment by khaihkd** [comment]
@larbofficial cannot get it back
