### ISSUE TITLE
OkGlobal Coin Singapore logo 

### ISSUE THREAD

**Issue by hsk77761** [tomochain/tokens#81]
**Token Address**
https://scan.tomochain.com/address/0x37c8c4fd1434de2d50be39079c14070172a3838f

**Token Symbol**
OKGSG

**Token Name**
OkGlobal Coin Singapore

**Token Logo**
![okglobal logo 256x256](https://user-images.githubusercontent.com/66628084/86508074-0a114400-bd92-11ea-99b7-035fc10a3f0c.png)

**Token Description**
Security Coin issued by OkGlobal Coin SWITCH Pte Ltd. Singapore

**Website**
https://okglobalcoinsg.com/

**Social links**
n/a

**Comment by thanhson1085** [comment]
Done
