### ISSUE TITLE
Toma classic

### ISSUE THREAD

**Issue by baris9076** [tomochain/tokens#91]
{
     " symbol " : " Tmc  " ,
     " name " : " Tomo classic" ,
     " description " : " TomoChain'in yerel belirteci " ,
     " web sitesi " : " https://tomochain.com " ,
     " topluluklar " : {
         " e-posta " : " admin@tomochain.com " ,
        " telgraf " :" https://t.me/tomochain " ,
         " reddit " : " https://www.reddit.com/r/Tomochain/ " ,
         " medium " : " https://medium.com/tomochain " ,
         " 
         " twitter " : " https://twitter.com/TomoChainANN " ,
         " facebook " :"https://www.facebook.com/tomochainofficial/ " ,
         " github " : " https://github.com/tomoc classic " ,
         " coinmarketcap " : " https://coinmarketcap.com/currencies/tomochain/ " ,
         " coingecko " : " https://www.coingecko.com/en/coins/tomochain "
    }
    
}

**Comment by khaihkd** [comment]
what is this?

**Comment by baris9076** [comment]
Toma classic

28 Tem 2020 Sal 12:30 tarihinde Do Minh Khai <notifications@github.com>
şunu yazdı:

**Comment by khaihkd** [comment]
why you use all TomoChain info.

**Comment by baris9076** [comment]
Deneme amaçlı yaptım

4 Ağu 2020 Sal 06:18 tarihinde Nguyen Sy Thanh Son <notifications@github.com>
şunu yazdı:
