### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Aponkhan998** [tomochain/tokens#94]
**Token Address**
e.g: https://scan.tomochain.com/address/0xa2fb8cb5f7cfb8fc99fb6c19d9a609fcc59dd96d

**Token Symbol**
e.g: Trx

**Token Name**
e.g: Trx Pro

**Token Logo**
![20200803_050220](https://user-images.githubusercontent.com/53684019/89134438-14685e80-d547-11ea-9754-c0e2363fea09.png)

**Token Description**
Same as Trx

**Website**
tron.org

**Social links**
e.g tron.org

**Comment by thanhson1085** [comment]
use Tron info is not allowed
