### ISSUE TITLE
Tomo classic 

### ISSUE THREAD

**Issue by baris9076** [tomochain/tokens#96]
" symbol " : " Tmc  " ,
 " name " : " Tomo classic" ,
 " description " : " Tomoclassic in yerel belirteci " ,
 " web sitesi " : " https://tomoclassic.com " ,

**Comment by khaihkd** [comment]
@baris9076 which contract address?

**Comment by baris9076** [comment]
0xEAeA5c3157C6B982685D59cd1C67E4Fc1ceB27E7

5 Ağu 2020 Çar 13:20 tarihinde Do Minh Khai <notifications@github.com> şunu
yazdı:

**Comment by khaihkd** [comment]
why the website does not work?

**Comment by khaihkd** [comment]
Sorry, we reject this issue. Because nothing shows on tomoscan for your info. The only website can be shown but it is not working, this is the reason we reject
